---
baseURL: "https://www.arborchurch.com/"
title: "Arbor Church"
languageCode: "en-us"
theme: "arbor"
timeZone: "America/Los_Angeles"
menu:
  main:
    - Name: About
      Weight: 10
    - Name: Get Involved
      Weight: 20
    - Name: Resources
      Weight: 30
    - Name: Give
      URL: https://arborchurch.churchcenteronline.com/giving?open-in-church-center-modal=true
      Identifier: Give
      Weight: 300
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  livestream:
    enabled: true
    youtube_id: BroiKlMfdRs
---
